ev/Vehicle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .views import *

admin.site.site_header = " "
# admin.site.site_title = "Admin Console"
admin.site.index_title = "Admin Console"
urlpatterns = [
    path('vehicle/', VehicleListView.as_view(), name='vehicle-list'),
    path('create/', vehicleCreateView.as_view(), name='vehicle-create'),
    path('<pk>/update/', VehicleUpdateView.as_view(), name='vehicle-update'),
    path('<pk>/delete/', VehicleDeleteView.as_view(), name='vehicle-delete'),

    path('battery/', BatteryListView.as_view(), name='battery-list'),
    path('battery/create/', BatteryCreateView.as_view(), name='battery-create'),
    path('battery/<pk>/update/', BatteryUpdateView.as_view(), name='battery-update'),
    path('battery/<pk>/delete/', BatteryDeleteView.as_view(), name='battery-delete'),

    path('device/', DeviceListView.as_view(), name='device-list'),
    path('device/create/', DeviceCreateView.as_view(), name='device-create'),
    path('device/<pk>/update/', DeviceUpdateView.as_view(), name='device-update'),
    path('device/<pk>/delete/', DeviceDeleteView.as_view(), name='device-delete'),

    path('driver/', DriverListView.as_view(), name='driver-list'),
    path('driver/create/', driver_registration_view, name='driver-create'),
    path('driver/<pk>/update/', DriverUpdateView.as_view(), name='driver-update'),
    path('driver/<pk>/delete/', DriverDeleteView.as_view(), name='driver-delete'),

    path('battery-autocomplete/', BatteryAutocomplete.as_view(),
         name="battery-autocomplete"),
    path('device-autocomplete/', DeviceAutocomplete.as_view(),
         name="device-autocomplete"),
]

ev/ev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.site.site_header = " "
# admin.site.site_title = "Admin Console"
admin.site.index_title = "Admin Console"
urlpatterns = [
    path('api/v1/', include('ev.apiurls')),
    path('', TemplateView.as_view(template_name='base/index.html'), name='home'),
    path('firebase/', TemplateView.as_view(template_name='webapp.html'),
         name='firebase'),
    path("vehicles/", include("Vehicle.urls"), name="vehicle"),
    path('dashboard/', include("Dashboard.urls"), name='dashboard'),
    path('report/', include("Report.urls"), name='report'),
    path('alert/', include("Alert.urls"), name='alert'),
    path('admin/', admin.site.urls),
    path("accounts/", include("account.urls"), name="account"),
    path("profiles/", include("Profile.urls"), name="profile"),
    path("password-change/", auth_views.PasswordChangeView.as_view(
        template_name="account/password_change.html"), name="password_change"),
    path("password-change-done/", auth_views.PasswordChangeDoneView.as_view(
        template_name="account/password_change_complete.html"), name="password_change_complete"),
]
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ev/Vehicle/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from account.models import Organization, UUIDModel
from Profile.models import Profile
# Create your models here.


class Device(UUIDModel):
    imei_number = models.CharField(
        verbose_name="IMEI Number",
        max_length=100
    )
    device_type = models.CharField(
        verbose_name="device type",
        max_length=100
    )
    onboarding_date = models.DateTimeField(
        default=timezone.now,
        verbose_name="onboarding date"
    )
    vehicle_scl_id = models.CharField(
        verbose_name="Vehicle SCL ID",
        max_length=50,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.imei_number

    def get_absolute_url(self):
        return reverse('device-list')


class Battery(UUIDModel):
    battery_number = models.CharField(
        verbose_name="battery number",
        max_length=50
    )
    capacity = models.CharField(
        verbose_name="battery capacity",
        max_length=100
    )
    onboarding_date = models.DateTimeField(
        default=timezone.now,
        verbose_name="onboarding date"
    )
    min_voltage = models.FloatField(
        verbose_name="minimum battery volatage", default=37)
    max_voltage = models.FloatField(
        verbose_name="maximum battery volatage", default=53)
    max_distance = models.FloatField(
        verbose_name="Maximum distance on full battery (km)", default=140)

    class Meta:
        verbose_name = "Battery"
        verbose_name_plural = "Batteries"

    def __str__(self):
        return self.battery_number

    def get_absolute_url(self):
        return reverse('battery-list')


class Vehicle(UUIDModel):
    vehicle_id = models.CharField(
        verbose_name="Vehicle Id",
        max_length=50
    )
    vin_number = models.CharField(
        verbose_name="VIN number",
        max_length=50,
        null=True,
        blank=True
    )

    device = models.ForeignKey(
        Device,
        related_name="vehicle",
        verbose_name="device",
        on_delete=models.CASCADE
    )
    battery_id = models.ForeignKey(
        Battery,
        related_name="vehicle",
        on_delete=models.CASCADE,
        verbose_name="battery id",
        max_length=255
    )
    make = models.CharField(
        verbose_name="make",
        max_length=50
    )
    model = models.CharField(
        verbose_name="model",
        max_length=50
    )
    year = models.CharField(
        verbose_name="year",
        max_length=4
    )
    tag = models.CharField(
        verbose_name="tag",
        max_length=255,
        blank=True,
        null=True
    )
    created_at = models.DateTimeField(
        auto_now=True,
        verbose_name="created at"
        )
    organization = models.ForeignKey(
        Organization, related_name="vehicles", null=True, blank=True, on_delete=models.SET_NULL)

    profile = models.ForeignKey(
        Profile, related_name="vehicles", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.vehicle_id

    def get_absolute_url(self):
        return reverse('vehicle-list')


class Driver(models.Model):
    name = models.CharField(
        verbose_name="driver name",
        max_length=255
    )
    phone_number = models.CharField(
        verbose_name="phone number",
        max_length=10
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('driver-list')


class Trip(UUIDModel):
    # profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        Profile, related_name="trips", on_delete=models.CASCADE, null=True, blank=True)
    source = models.CharField(max_length=500)
    destination = models.CharField(max_length=500)
    start = models.DateTimeField()
    end = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(
        auto_now=True,
        verbose_name="created at"
        )


class LiveStatus(models.Model):
    asset_uid = models.CharField(max_length=64, blank=True, null=True)
    data_capture_time = models.CharField(
        max_length=50, verbose_name="data capture time (yyyy-mm-dd-hh)")
    latitude = models.CharField(max_length=15, verbose_name="device lat")
    longitude = models.CharField(max_length=15, verbose_name="device long")
    device_id = models.CharField(max_length=100)
    speed = models.CharField(max_length=100)
    account_id = models.CharField(max_length=50)
    engine_state = models.CharField(max_length=5)
    battery_voltage = models.CharField(max_length=10)
    created_at = models.DateField(
        auto_now=True,
        verbose_name="created at"
        )

    def __str__(self):
        return self.device_id

ev/Vehicle/forms.py
from django.forms import ModelForm
from .models import Vehicle, Battery, Device, Driver
from django.contrib.auth.forms import UserCreationForm
from django import forms
from account.models import Account
from Profile.models import Profile
from dal import autocomplete


class VehicleForm(ModelForm):
    class Meta:
        model = Vehicle
        fields = ("vehicle_id", "make", "model",
                  "battery_id", "device", "year", "tag", "vin_number",)
        widgets = {
            'battery_id': autocomplete.ModelSelect2(url='battery-autocomplete'),
            'device': autocomplete.ModelSelect2(url='device-autocomplete')
        }


class VehicleUpdateForm(ModelForm):
    class Meta:
        model = Vehicle
        fields = ("vehicle_id", "make", "model",
                  "battery_id", "device", "year", "tag", "vin_number",)
        widgets = {
            'battery_id': autocomplete.ModelSelect2(url='battery-autocomplete'),
            'device': autocomplete.ModelSelect2(url='device-autocomplete')
        }


class BatteryForm(ModelForm):
    class Meta:
        model = Battery
        fields = '__all__'


class DeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = '__all__'


class DriverForm(ModelForm):
    class Meta:
        model = Driver
        fields = '__all__'


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        max_length=100, help_text="Required. Add a valid email address.")

    class Meta:
        model = Account
        fields = ("email", "password1", "password2")

ev/templates/vehicles/create_vehicle.html
{% extends "main.html" %}
{% load static %}
{% load bootstrap4 %}
{% block content %}




<form action="{% url 'vehicle-create' %}" method="POST">
  {% csrf_token %}
  <div class="form-group row">
    <label class="col-md-2 col-form-label" for="id_vehicle_id">Vehicle Id</label>
    <div class="col-md-3">
      <input type="text" name="vehicle_id" maxlength="50" class="form-control"  placeholder="Vehicle Id" title="" required="" id="id_vehicle_id">

    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-2 col-form-label" for="id_make">Make</label>
    <div class="col-md-3">
      <input type="text" name="make" maxlength="50" class="form-control"  placeholder="Make" title="" required="" id="id_make">
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-2 col-form-label" for="id_model">Model</label>
    <div class="col-md-3">
      <input type="text" name="model" maxlength="50" class="form-control"  placeholder="Model" title="" required="" id="id_model">
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-2 col-form-label" for="id_battery_id">Battery</label>
    <div class="col-md-3">
      {{form.battery_id}}
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-2 col-form-label" for="id_device">Device</label>
    <div class="col-md-3">
      {{form.device}}
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-2 col-form-label" for="id_year">Year</label>
    <div class="col-md-3">
      <input type="text" name="year" maxlength="50" class="form-control"  placeholder="Year" title="" required="" id="id_year">
    </div>
  </div>

  <div class="form-group row">
    <label class="col-md-2 col-form-label" for="id_tag">Tag</label>
    <div class="col-md-3">
      <input type="text" name="tag" maxlength="50" class="form-control"  placeholder="Tag" title="" required="" id="id_tag">
    </div>
  </div>

  

  <div class="form-group row">
    <label class="col-md-2 col-form-label" for="id_vin_number">VIN Number</label>
    <div class="col-md-3">
      <input type="text" name="vin_number" maxlength="50" class="form-control"  placeholder="vin_number" title="" required="" id="vin_number">
    </div>
  </div>

  <button type="submit" class="btn btn-primary">Create</button>

</form>



<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}

<script>
(function($) {
    $('#add-form').click(function() {
        var index = $('#id_inline_test_models-TOTAL_FORMS').val()
        var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
        newTable.find(':input').each(function() {
            for (attr of ['name', 'id'])
                $(this).attr(
                    attr,
                    $(this).attr(attr).replace('__prefix__', index)
                )
        })
        newTable.insertBefore($(this))
        $('#id_inline_test_models-TOTAL_FORMS').val(
            parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
        )
        newTable.slideDown()
    })
})($)
</script>

{% endblock %}

ev/templates/vehicles/delete_vehicle.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

  <form  action="{% url 'vehicle-delete' vehicle.id %}" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{vehicle.vehicle_id}} ?</p>
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
  </form>

{% endblock %}

ev/templates/vehicles/update_vehicle.html
{% extends "main.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
  <h3>Update vehicle</h3>
  <br>

  <form  action="{% url 'vehicle-update' vehicle.pk %}" method="post">
    {% csrf_token %}
    <div class="form-group row">
      <label class="col-md-2 col-form-label" for="id_vehicle_id">Vehicle Id</label>
      <div class="col-md-3">
        <input type="text" name="vehicle_id" maxlength="50" class="form-control" value="{{vehicle.vehicle_id}}" placeholder="Vehicle Id" title="" required="" id="id_vehicle_id">

      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label" for="id_make">Make</label>
      <div class="col-md-3">
        <input type="text" name="make" maxlength="50" class="form-control" value="{{vehicle.make}}" placeholder="Vehicle Id" title="" required="" id="id_make">
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label" for="id_model">Model</label>
      <div class="col-md-3">
        <input type="text" name="model" maxlength="50" class="form-control" value="{{vehicle.model}}" placeholder="Vehicle Id" title="" required="" id="id_model">
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label" for="id_battery_id">Battery</label>
      <div class="col-md-3">
        {{form.battery_id}}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label" for="id_device">Device</label>
      <div class="col-md-3">
        {{form.device}}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label" for="id_year">Year</label>
      <div class="col-md-3">
        <input type="text" name="year" maxlength="50" class="form-control" value="{{vehicle.year}}" placeholder="Vehicle Id" title="" required="" id="id_year">
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label" for="id_tag">Tag</label>
      <div class="col-md-3">
        <input type="text" name="tag" maxlength="50" class="form-control" value="{{vehicle.tag}}" placeholder="Vehicle Id" title="" required="" id="id_tag">
      </div>
    </div>

    
    <div class="form-group row">
      <label class="col-md-2 col-form-label" for="id_vin_number">VIN Number</label>
      <div class="col-md-3">
        <input type="text" name="vin_number" maxlength="50" class="form-control" value="{{vehicle.vin_number}}" placeholder="vin_number" title="" required="" id="vin_number">
      </div>
    </div>



      <div class="form-group row">
        <div class="col-md-1">
          <button type="submit" name="button" value="update" class="btn btn-primary">Update</button>
        </div>

        <div class="btn btn-danger">
          <a href="{% url 'vehicle-delete' vehicle.id %}" class="deletelink" style="text-decoration: none;color: #fff;">Delete</a>
        </div>
      </div>


  </form>
<br>

<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}



<script>

(function($) {
  console.log("hell")
    $('#add-form').click(function() {
        var index = $('#id_inline_test_models-TOTAL_FORMS').val()
        var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
        newTable.find(':input').each(function() {
            for (attr of ['name', 'id'])
                $(this).attr(
                    attr,
                    $(this).attr(attr).replace('__prefix__', index)
                )
        })
        newTable.insertBefore($(this))
        $('#id_inline_test_models-TOTAL_FORMS').val(
            parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
        )
        newTable.slideDown()
    })



})($)
</script>

<script type="text/javascript">
  $(document).ready(function() {
    console.log("yoooo")
    var auto = document.getElementsByClassName("select2-selection__rendered");
    console.log(auto.length)
    for (var i = 0; i < auto.length; i++) {
      auto[i].style.lineHeight = '16px';
      console.log("lol");
    }
  });
</script>

{% endblock %}

ev/templates/vehicles/vehicles_list.html
{% extends "main.html" %}
{% load static %}

{% block content %}



{% include 'add_search.html' with search='vehicle-list' add='vehicle-create' filter=vehicles_filter placeholder='Search' %}

<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col"></th>
      <th scope="col">Vehicle Id</th>
      <th scope="col">Make</th>
      <th scope="col">Model</th>
      <th scope="col">Battery</th>
    </tr>
  </thead>
  <tbody>
    {% if vehicles %}
    {% for vehicle in vehicles %}
    <tr>
      <th scope="row"></th>
      {% if request.user.is_superuser %}
      <td><a href="{% url 'vehicle-update' vehicle.id %}">{{vehicle.vehicle_id}}</a></td>
      {% else %}
      <td>{{vehicle.vehicle_id}}</td>
      {% endif %}
      <td>{{vehicle.make}}</td>
      <td>{{vehicle.model}}</td>
      <td>{{vehicle.battery_id}}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr class="no-data">
    <td colspan="14">No Record !!</td>
    </tr>
    {% endif %}
  </tbody>
</table>

{% endblock %}