ev/ev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.site.site_header = " "
# admin.site.site_title = "Admin Console"
admin.site.index_title = "Admin Console"
urlpatterns = [
    path('api/v1/', include('ev.apiurls')),
    path('', TemplateView.as_view(template_name='base/index.html'), name='home'),
    path('firebase/', TemplateView.as_view(template_name='webapp.html'),
         name='firebase'),
    path("vehicles/", include("Vehicle.urls"), name="vehicle"),
    path('dashboard/', include("Dashboard.urls"), name='dashboard'),
    path('report/', include("Report.urls"), name='report'),
    path('alert/', include("Alert.urls"), name='alert'),
    path('admin/', admin.site.urls),
    path("accounts/", include("account.urls"), name="account"),
    path("profiles/", include("Profile.urls"), name="profile"),
    path("password-change/", auth_views.PasswordChangeView.as_view(
        template_name="account/password_change.html"), name="password_change"),
    path("password-change-done/", auth_views.PasswordChangeDoneView.as_view(
        template_name="account/password_change_complete.html"), name="password_change_complete"),
]
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ev/Profile/models.py
from django.db import models
from account.models import Account, Organization, UUIDModel
from ev.helpers import get_image_upload_path
from ev.storages import ProfilePicStorageS3, KtpStorageS3, SimStorageS3
from django.conf import settings


class Role(UUIDModel):
    name = models.CharField(max_length=50, default="user")

    def __str__(self):
        return self.name


class Profile(UUIDModel):
    DRIVER = "driver"
    MANAGER = "manager"
    PROFILE_CHOICES = (
        (DRIVER, "Driver"),
        (MANAGER, "Manager")
    )

    ACCEPTED = "accepted"
    REJECTED = "rejected"
    PENDING = "pending"

    DOCUMENT_VERIFICATION_STATUS_CHOICES = (
        (ACCEPTED, "Accepted"),
        (REJECTED, "Rejected"),
        (PENDING, "Pending")
    )

    user = models.OneToOneField(
        Account, on_delete=models.CASCADE, related_name="profile")
    first_name = models.CharField(max_length=50, verbose_name="first name")
    last_name = models.CharField(max_length=50, verbose_name="last name")
    ktp_number = models.CharField(blank=True, null=True,
                                  max_length=100, verbose_name="KTP Number")
    sim_number = models.CharField(blank=True, null=True,
                                  max_length=100, verbose_name="SIM Number")
    profile_type = models.CharField(
        max_length=100, verbose_name="Profile Type",
        choices=PROFILE_CHOICES, default=DRIVER
        )
    role = models.ForeignKey(Role, related_name="profile",
                             on_delete=models.SET_NULL, blank=True, null=True)
    ktp_image = models.ImageField(
        default="ktp/bg2.png", null=True, blank=True, upload_to="ktp")
    sim_image = models.ImageField(
        default="ktp/bg2.png", null=True, blank=True, upload_to="sim")
    document_verification_status = models.CharField(
        max_length=100,
        choices=DOCUMENT_VERIFICATION_STATUS_CHOICES,
        default=PENDING,
        verbose_name="Verification Status"
    )
    organization = models.ForeignKey(
        Organization, on_delete=models.SET_NULL, null=True, blank=True)
    address = models.TextField(null=True, blank=True, verbose_name="Address")
    profile_picture = models.ImageField(
        null=True,
        blank=True,
        upload_to=get_image_upload_path,
        storage=ProfilePicStorageS3()
    )

    def __str__(self):
        return (self.first_name + ' ' + self.profile_type)

    @property
    def profile_picture_url(self):
        try:
            return self.profile_picture.url
        except:
            return settings.DEFAULT_PROFILE_PICTURE_URL

ev/templates/driver/create_driver.html
{% extends "main.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
<h4>Create Driver</h4>
<br>
<form  action="{% url 'driver-create' %}" method="post">
  {% csrf_token %}
  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_form registration_form layout="horizontal"%}
    </div>
  </div>



  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_field profile_form.first_name layout="horizontal" %}
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_field profile_form.last_name layout="horizontal" %}
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_field profile_form.ktp_number layout="horizontal" %}
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_field profile_form.sim_number layout="horizontal" %}
    </div>
  </div>

  {% if request.user.is_admin %}
  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_field profile_form.organization layout="horizontal" %}
    </div>
  </div>
  {% else %}
<div class="col-md-6">
  <div class="form-group">
    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_organization">Organization</label>
      <div class="col-md-9">
        <select name="organization" class="form-control" title="" id="id_organization" readonly>
        <option value="{{request.user.profile.organization.id}}" selected="">{{request.user.profile.organization}}</option>
        </select>
      </div>
    </div>
  </div>
  </div>
  {% endif %}

  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_field profile_form.ktp_image layout="horizontal" %}
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_field profile_form.sim_image layout="horizontal" %}
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      {% bootstrap_field profile_form.document_verification_status layout="horizontal" %}
    </div>
  </div>



  <div class="col-md-4">
    <div class="form-group">
      {% bootstrap_button "Register" button_type="submit" button_class="btn-primary" %}
    </div>
  </div>

</form>

{% endblock %}

ev/templates/driver/delete_driver.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

  <form  action="{% url 'driver-delete' driver.id %}" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{driver.name}} ?</p>
    <button type="submit" class="btn btn-danger">Confirm Delete</button>
  </form>

{% endblock %}

ev/templates/driver/driver_list.html
{% extends "main.html" %}
{% load static %}

{% block content %}




<div class="input-group" style="width:100%; padding:10px;">
  <form action="{% url 'driver-list'  %}" style="width:33%; flex:none float:left;" method="GET">
      <input type="text" name="search" class="form-control rounded"  placeholder="Search for Driver" value="{{ driver_filter.form.search.value|default:'' }}">
</form>

  <div class="" style="width:55%; flex:none float:left;"></div>

  <div  class="btn btn-success" style="width:7%; flex:none float:left; ">
    <a href="{% url 'driver-create' %}" style="color:white">ADD</a>
  </div>


</div>




<table class="table">
  <thead class="table-dark">
    <tr>
      <th scope="col"></th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">KTP</th>
      <th scope="col">Vehicles</th>
    </tr>
  </thead>
  <tbody>
    {% if drivers %}
    {% for driver in drivers %}
    <tr>
      <th scope="row"></th>
      <td><a href="{% url 'driver-update' driver.id %}">{{driver.first_name}}</a></td>
      <td>{{driver.last_name}}</td>
      <td>{{driver.ktp_number}}</td>
      <td>{{driver.vehicles.count}}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr class="no-data">
    <td colspan="14">No Record !!</td>
    </tr>
    {% endif %}
  </tbody>
</table>


{% endblock %}

ev/templates/driver/update_driver.html
{% extends "main.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
  <h3>Update Driver</h3>
  <br>
  <form  action="{% url 'driver-update' driver.pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_first_name">First Name</label>
      <div class="col-md-3">
        <input type="text" name="first_name" value="{{driver.first_name}}" maxlength="200" class="form-control" placeholder="First Name" title="" required="" id="id_first_name" readonly>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_last_name">Last Name</label>
      <div class="col-md-3">
        <input type="text" name="last_name" value="{{driver.last_name}}" maxlength="200" class="form-control" placeholder="Last Name" title="" required="" id="id_last_name" readonly>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_ktp_number">KTP Number</label>
      <div class="col-md-3">
        <input type="text" name="ktp_number" value="{{driver.ktp_number}}" maxlength="200" class="form-control" placeholder="KTP" title="" required="" id="id_ktp_number" readonly>
      </div>
    </div>


    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_ktp_image">KTP image</label>
      {% if driver.ktp_image %}
      <div class="col-md-1">
        <img id="ktp_img" src="{{driver.ktp_image.url}}" width="60" height="80" />
      </div>
      {% endif %}
      <div class="col-md-1">
          <input type="file" name="ktp_image" accept="image/*" class="form-control-file" title="" id="id_ktp_image" onchange="ktpImage(this);">
      </div>
    </div>




    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_sim_image">Sim image</label>
      {% if driver.sim_image %}
      <div class="col-md-1">
          <img src="{{ driver.sim_image.url }}" width="60" height="80" id="sim_img"/>
      </div>
      {% endif %}
      <div class="col-md-1">
        <input type="file" name="sim_image" accept="image/*" class="form-control-file" title="" id="id_sim_image" onchange="simImage(this);">
      </div>

    </div>

    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_document_verification_status">Verification Status</label>
      <div class="col-md-3">
        <input type="text" name="document_verification_status" value="{{driver.document_verification_status}}" maxlength="200" class="form-control" placeholder="KTP" title="" required="" id="id_document_verification_status" readonly>
      </div>
      {% if driver.document_verification_status != "accepted" %}
        <div class="col-md-1">
          <button type="submit" name="button" value="accept" class="btn btn-success">Approve</button>
        </div>
      {% endif %}
      {% if driver.document_verification_status != "rejected" %}
        <div class="col-md-1">
          <button type="submit" name="button" value="reject" class="btn btn-danger">Reject</button>
        </div>
      {% endif %}
      {% if driver.document_verification_status != "pending" %}
        <div class="col-md-1">
          <button type="submit" name="button" value="pending" class="btn btn-warning">Pending</button>
        </div>
      {% endif %}
    </div>

    {% if request.user.is_superuser %}
    {% bootstrap_field form.organization layout="horizontal" field_class="col-md-3"%}
    {% else %}
    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_organization">Organization</label>
      <div class="col-md-3">
        <input type="hidden" name="organization" value="{{driver.organization.id}}" maxlength="200" class="form-control" placeholder="KTP" title="" required="" id="id_organization" readonly>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-3 col-form-label" for="id_org">Organization</label>
      <div class="col-md-3">
        <input type="text" name="org" value="{{driver.organization}}" maxlength="200" class="form-control" placeholder="KTP" title="" required="" id="id_organization" readonly>
      </div>
    </div>
    {% endif %}

    {% if driver.document_verification_status == "accepted" %}

      {% if assigned_vehicles or available_vehicles %}

      <table class="table">
        <thead class="table-dark">
          <tr>
            <th scope="col">
              <input type="checkbox" onclick='selects()' name="select_all"/> Select All<br/>
            </th>
            <th scope="col">Vehicle Id</th>
            <th scope="col">Make</th>
            <th scope="col">Model</th>
            <th scope="col">Battery</th>
          </tr>
        </thead>
        <tbody>
          {% if assigned_vehicles %}
          {% for vehicle in assigned_vehicles %}
          <tr>
            <th scope="row">
              <input type="checkbox" name="vehicles" value="{{vehicle.id}}" checked><br/>
            </th>
            <td><a href="{% url 'vehicle-update' vehicle.id %}">{{vehicle.vehicle_id}}</a></td>
            <td>{{vehicle.make}}</td>
            <td>{{vehicle.model}}</td>
            <td>{{vehicle.battery_id}}</td>
          </tr>
          {% endfor %}
          {% endif %}
          {% if available_vehicles %}
          {% for vehicle in available_vehicles %}
          <tr>
            <th scope="row">
              <input type="checkbox" name="vehicles" value="{{vehicle.id}}"><br/>
            </th>
            <td><a href="{% url 'vehicle-update' vehicle.id %}">{{vehicle.vehicle_id}}</a></td>
            <td>{{vehicle.make}}</td>
            <td>{{vehicle.model}}</td>
            <td>{{vehicle.battery_id}}</td>
          </tr>
          {% endfor %}

          {% endif %}
        </tbody>
      </table>
      {% else %}
      <strong>Not enough vehicles to assign </strong>
      <br>
      {% endif %}
    {% else %}
      <strong>Cannot assign vehicle to an unverified Driver</strong>
      <br>
    {% endif %}

      <br>


      <div class="form-group row">
        <div class="col-md-1">
          <button type="submit" name="button" value="update" class="btn btn-primary">Update</button>
        </div>

        <div class="col-md-6">
          <button type="submit" name="button" value="remove" class="btn btn-danger">Remove</button>
        </div>
      </div>
  </form>
<br>



<script type="text/javascript">
  function selects(){
      var ele=document.getElementsByName('vehicles');
      var sel=document.getElementsByName('select_all');
      for(var i=0; i<ele.length; i++){
          if(ele[i].type=='checkbox'){
            if(sel.checked){
              console.log("select is check'")
              ele[i].checked=false;
            }
            else{
              console.log("select is not check'")
              ele[i].checked=true;
            }

          }


      }
      if(sel.checked){
        sel.checked=false;
      }
      else{
        sel.checked=true;
      }
  }

  function ktpImage(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            var ktp = document.getElementById("ktp_img");
            ktp.src = e.target.result;
          };

          reader.readAsDataURL(input.files[0]);
      }
  }

  function simImage(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
            var sim = document.getElementById("sim_img");
            sim.src = e.target.result;
          };

          reader.readAsDataURL(input.files[0]);
      }
  }
</script>




{% endblock %}